spring:

  application:
    name: flash-sale-engine
    admin:
      enabled:
  cache:
    type: redis


  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:flash_sale_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

      lettuce:
        pool:
          max-active: 100
          max-idle: 50
          min-idle: 2
          max-wait: 1000ms

ratelimit:
  policies:
    AUTH:
      algorithm: SLIDING_WINDOW
      requests: 5
      window: 60

    TRANSACTION:
      algorithm: TOKEN_BUCKET
      requests: 10
      window: 60
      burst: 20
      refill: 0.1667

    GENERAL:
      algorithm: FIXED_WINDOW
      requests: 300
      window: 60

    ADMIN:
      algorithm: TOKEN_BUCKET
      requests: 100
      window: 60
      burst: 200
      refill: 1.6667

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXNhbXBsZS1kZXZlbG9wbWVudC1zZWNyZXQta2V5LXdoY2gtaXMtbG9uZy1lbm91Z2g=}
  expiration: 86400000

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true

    readinessstate:
      enabled: true
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}