name: Continuous Integration

on:
  push:
    branches:
      - main
      - feature/**
      - ops/**

  pull_request:
    branches:
      - main
      - feature/**
      - ops/**

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "GitHub Actions is working!"